\input texinfo @c -*-texinfo-*-

@c %**start of header
@setfilename libbow.info
@settitle Programmer's Guide to the Bag-Of-Words Library
@c %**end of header

@ifinfo
@format
START-INFO-DIR-ENTRY
* Libbow::                      Bag-Of-Words Library
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@c set the vars LIBBOW_VERSION
@include version.texi

@ifinfo
This file documents the features and implementation of The Bag-Of-Words
Library. 

Copyright (C) 1996 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that the
section entitled ``GNU Library General Public License'' is included exactly as
in the original, and provided that the entire resulting derived work is
distributed under the terms of a permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that the section entitled ``GNU Library General Public License'' and
this permission notice may be included in translations approved by the
Free Software Foundation instead of in the original English.
@end ifinfo

@titlepage
@title Programmer's Guide to the
@title Bag-Of-Words Library
@sp 3
@c @subtitle last updated October 1996
@subtitle Version @value{LIBBOW_VERSION}
@author Andrew Kachites McCallum (mccallum@@cs.cmu.edu)
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1996 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that the
section entitled ``GNU Library General Public License'' is included exactly as
in the original, and provided that the entire resulting derived work is
distributed under the terms of a permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that the section entitled ``GNU Library General Public License'' may be
included in a translation approved by the author instead of in the original
English.
@end titlepage

@node Top, 

@ifinfo
This manual documents how to install and use The Bag-Of-Words Library
(or @samp{libbow}), version @value{LIBBOW_VERSION}.
@end ifinfo

@menu
@end menu

@node Overview
@chapter Overview

@node Traversing Diretories to get Text Files

@node Getting Words from Text Files

@node Mapping between Words and Integers

@node Creating a Word Vector from a Text File

@node Writing and Reading Word Vectors as Data Files

@bye
